[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
rocksdb = "0.19.0"
chrono = "0.4.22"
[dependencies.dirs]
version = "4.0"